language: node_js
node_js: [node]

before_install:
  # Export the C++11 compiler.
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi

cache: yarn

env:
  # Do multiple runs for testing and linting.
  matrix:
    - TEST_TYPE=cov
    - TEST_TYPE=lint:eslint
    - TEST_TYPE=lint:prettier

before_script:
  # When linting, build the dependencies so they can be resolved.
   - yarn build
script:
  # Run testing or linting depending on the environment.
  - |
    set -e
    yarn $TEST_TYPE
    set +e
after_script:
  - npminstall codecov && codecov